const express = require('express')
const app = express()
const passport = require('../helper/passport')
app.use(passport.initialize())


const {checkisAuthenticated,checknotAuthenticated,PassportAuthenticate} = require('../helper/authenticator')
const usercontroller = require('../controllers/usercontroller')
const servicecontroller =  require('../controllers/servicecontroller')
const dentistcontroller =  require('../controllers/dentistcontroller')
const medicinecontroller = require('../controllers/medicinecontroller')
const branchcontroller = require('../controllers/branchcontroller')
const transactioncontroller = require('../controllers/transactioncontroller')
const schedulecontroller = require('../controllers/schedulecontroller')
const reservationcontroller = require('../controllers/reservationcontroller')
const notificationcontroller = require('../controllers/notificationcontroller')
const dashboardcontroller = require('../controllers/dashboardcontroller')
const feedbackcontroller = require('../controllers/feedbackcontroller')
const reportcontroller = require('../controllers/reportcontroller')
const user = require('../dataaccess/user')


app.get('/dashboard/getData/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,dashboardcontroller.getData)
app.get('/dashboard/dentistTransaction/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,dashboardcontroller.dentistTransaction)

app.post('/user/register',usercontroller.save)
app.post('/user/changearchivestatus',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.changearchivestatus)
app.post('/user/save',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.save)
app.post('/user/saveuser_superadmin',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.saveuser_superadmin)
app.patch('/user/updateuser_superadmin/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.updateuser_superadmin)
app.get('/user/getlist',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.getlist)
app.get('/user/getlist/(:user)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.getUser)
app.patch('/user/update/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.update)
app.patch('/user/archive/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.archive)
app.patch('/user/archive/(:idno)/(:status)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.archivebystatus)

app.patch('/user/changepass/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.changepass)
app.patch('/user/changepassEmployee/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.changepassEmployee)
app.post('/user/changepic',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.changepic)
app.post('/user/search',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.search)

app.delete('/user/remove/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.remove)
app.get('/user/details/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.getDetails)

app.get('/user/list/(:type)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.getUserList)
app.get('/user/list/(:type)/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.getUsersbyArchive)

app.post('/user/addpatient',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.addPatient)
app.post('/user/searchPatient',PassportAuthenticate(passport),checkisAuthenticated,usercontroller.searchPatient)
app.get('/getSchedules',PassportAuthenticate(passport),checkisAuthenticated,schedulecontroller.getSchedules)
app.get('/getSchedules/(:branchid)',PassportAuthenticate(passport),checkisAuthenticated,schedulecontroller.getSchedulesByBranch)
app.post('/updateSchedule',PassportAuthenticate(passport),checkisAuthenticated,schedulecontroller.updateSchedule)


app.get('/service/list/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,servicecontroller.getlist)
app.post('/service/save',PassportAuthenticate(passport),checkisAuthenticated,servicecontroller.save)
app.patch('/service/archive/(:idno)/(:status)',PassportAuthenticate(passport),checkisAuthenticated,servicecontroller.archive)
app.patch('/service/update/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,servicecontroller.update)
app.post('/service/search',PassportAuthenticate(passport),checkisAuthenticated,servicecontroller.search)

app.get('/medicine/list/(:branch)/(:type)',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.getlist)
app.post('/medicine/save',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.save)
app.patch('/medicine/archive/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.archive)
app.patch('/medicine/retrieve/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.retrieve)
app.patch('/medicine/update/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.update)
app.post(`/medicine/addstock`,PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.addstock)
app.post('/medicine/getStocksin',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.getStocksin)
app.post('/medicine/getInfo',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.getInfo)
app.post('/medicine/search',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.search)
app.post('/medicine/stockinfo',PassportAuthenticate(passport),checkisAuthenticated,medicinecontroller.stockinfo)


app.post('/branch/save',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.save)
app.get('/branch/list',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.list)
app.get('/branch/list/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.listbyarchive)
app.get('/branch/publicList',branchcontroller.publicList)
app.patch('/branch/remove',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.remove)
app.patch('/branch/archivelist',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.archivelist)
app.patch('/branch/update',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.update)
app.get('/branch/getListUser/(:type)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListUser)
app.get('/branch/getListUser/(:type)/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListUserbyArchive)
app.get('/branch/getListService',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListService)
app.get('/branch/getListServiceByArchive/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListServiceByArchive)
app.get('/branch/getListDentist',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListDentist)

app.get('/branch/getListDentistbyArchive/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListDentistbyArchive)


app.get('/branch/getListMedicine/(:type)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListMedicine)
app.get('/branch/getListMedicine/(:type)/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListMedicineByArchive)
app.get('/branch/getListAllInfo',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getListAllInfo)
app.get('/branch/getInfo/(:idno)/(:type)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.getInfo)
app.get('/branch/search/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,branchcontroller.search)

app.get('/dentist/list',PassportAuthenticate(passport),checkisAuthenticated,dentistcontroller.getlist)
app.post('/dentist/save',PassportAuthenticate(passport),checkisAuthenticated,dentistcontroller.save)
app.patch('/dentist/archive/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,dentistcontroller.archive)
app.patch('/dentist/archive/(:idno)/(:archive)',PassportAuthenticate(passport),checkisAuthenticated,dentistcontroller.archivebystatus)
app.patch('/dentist/update/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,dentistcontroller.update)
app.post('/dentist/search',PassportAuthenticate(passport),checkisAuthenticated,dentistcontroller.search)

app.post('/transaction/save',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.save)
app.get('/transaction/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.getTransaction)
app.post('/transaction/action/save',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.actionsave)
app.post('/transaction/action/removeMedicineused',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.removeMedicineused)
app.post('/transaction/action/updateMedicineused',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.updateMedicineused)
app.post('/transaction/action/addMedicineused',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.addMedicineused)
app.delete('/transaction/action/remove/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.removeaction)
app.patch('/transaction/action/update/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.updateaction)
app.post('/transaction/editStatus',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.editStatus)
app.patch('/transaction/editType/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.editType)
app.post('/transaction/savePrescription',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.createPrescription)
app.post('/transaction/removePrescription',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.removePrescription)
app.post('/transaction/updatePrescription',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.updatePrescription)
app.get('/transaction/prescriptionInfo/(:idno)',PassportAuthenticate(passport),transactioncontroller.prescriptionInfo)
app.get('/transaction/prescriptInfoByRef/(:refno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.prescriptInfoByRef)
app.post('/transaction/removeTreatment',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.removeTreatment)
app.patch('/transaction/additionalTreatment/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.additionalTreatment)
app.get('/transaction/get/(:status)/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.getTransactionByStatus)
app.get('/transaction/get/(:status)/(:branch)/(:userid)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.getUserTransactionWalkIn)
app.post('/transaction/createBillPharmarcy',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.createBillPharmarcy)
app.patch('/transaction/updateActualTreatmentAmount',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.updateActualTreatmentAmount)
app.post('/transaction/createBillTreatment',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.createBillTreatment)
app.get('/transaction/viewBill/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.viewBill)
app.post('/transaction/getRecords',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.getRecords)
app.patch('/transaction/saveMedRemarks',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.saveMedRemarks)
app.patch('/transaction/addDiscount',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.addDiscount)
app.post('/transaction/getPastListPharmacy',PassportAuthenticate(passport),checkisAuthenticated,transactioncontroller.getPastListPharmacy)

app.post('/reservation/create',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.create)
app.get('/reservation/get/(:status)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getReservation)
app.post('/reservation/get/(:status)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getReservationPaginate)
app.get('/reservation/info/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.reservationInfo)
app.patch('/reservation/deny/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.deny)
app.patch('/reservation/cancel/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.cancel)
app.patch('/reservation/confirm/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.confirm)
app.get('/reservation/activelist/(:date)/(:dentist)/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getActiveListDay)
app.post('/reservation/patient',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getPatientReservations)
app.post('/reservation/getApprovedTimeDay',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getApprovedTimeDay)
app.post('/reservation/appointments',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.appointments)
app.post('/reservation/proceedTransaction',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.proceedTransaction)
app.post('/reservation/createFollowupReservation',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.createFollowupReservation)
app.post('/reservation/changeReservationDate',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.changeReservationDate)
app.get('/reservation/getReservationFollowup/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getReservationFollowup)
app.delete('/reservation/deleteReservation/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.deleteReservation)
app.post('/reservation/list',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.list)
app.post('/reservation/changeTimeReservation',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.changeTimeReservation)
app.post('/reservation/createWalkInReservation',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.createWalkInReservation)
app.post('/reservation/getNextAppointment',PassportAuthenticate(passport),checkisAuthenticated,reservationcontroller.getNextAppointment)


app.get('/notification/get/(:admin)',PassportAuthenticate(passport),checkisAuthenticated,notificationcontroller.getNotification)
app.patch('/notification/markasRead/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,notificationcontroller.markasRead)
app.patch('/notification/markasReadpatient/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,notificationcontroller.markasReadpatient)
app.post('/notification/message/create',PassportAuthenticate(passport),checkisAuthenticated,notificationcontroller.messageCreate)
app.patch('/notification/messageMarkasRead/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,notificationcontroller.messageMarkasRead)

app.post('/feedback/save',PassportAuthenticate(passport),checkisAuthenticated,feedbackcontroller.save)
app.get('/feedback/patientget/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,feedbackcontroller.patientget)
app.get('/feedback/adminget/(:branch)',PassportAuthenticate(passport),checkisAuthenticated,feedbackcontroller.adminget)
app.delete('/feedback/remove/(:idno)',PassportAuthenticate(passport),checkisAuthenticated,feedbackcontroller.remove)

app.post('/reports/billingRecords',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.billingRecords)
app.post('/reports/sales_daily',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.sales_daily)
app.post('/reports/sales_monthly',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.sales_monthly)
app.post('/reports/sales_yearly',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.sales_yearly)
app.post('/reports/pharmacyPurchaseRecords',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.pharmacyPurchaseRecords)
app.post('/reports/pharmacy_daily',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.pharmacy_daily)
app.post('/reports/pharmacy_monthly',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.pharmacy_monthly)
app.post('/reports/pharmacy_yearly',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.pharmacy_yearly)
app.post('/reports/appointment_daily',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.appointment_daily)
app.post('/reports/appointment_monthly',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.appointment_monthly)
app.post('/reports/appointment_yearly',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.appointment_yearly)
app.post('/reports/getByGender',PassportAuthenticate(passport),checkisAuthenticated,reportcontroller.getByGender)
<<<<<<< HEAD

=======
>>>>>>> version5

module.exports = app
